### ISSUE TITLE
 Address already in use   when using  ss-python as Backend Type

### ISSUE THREAD

**Issue by YanceyWang** [librehat/shadowsocks-qt5#47]
when i choose `ShadowSocksPython` as Backend Type
ss-Qt5 can not be  started  for `Address already in use`, even thought i restart my PC
log shows:
```javascript
2015-01-21 15:38:21 INFO     loading libcrypto from libcrypto.so.1.0.0
2015-01-21 15:38:21 INFO     starting local at 127.0.0.1:1080
2015-01-21 15:38:21 ERROR    [Errno 98] Address already in use
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/shadowsocks/local.py", line 60, in main
    udp_server = udprelay.UDPRelay(config, dns_resolver, True)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/udprelay.py", line 127, in __init__
    server_socket.bind((self._listen_addr, self._listen_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
```
and `libQtShadowSocks` works fine for me.
how to solve this?
thx ;)

**Comment by librehat** [comment]
Are you using the latest python port?

And could you please try to start `sslocal` which is the local client of shadowsocks-python in terminal (or `cmd`)?

**Comment by YanceyWang** [comment]
My python version is `Python 2.7.6` 
and **sslocal** works fine for me 
```java
xxx@xxx ~/antiWall $ sslocal -c congfig.json 
INFO: loading config from congfig.json
shadowsocks 2.6.4
2015-01-22 09:52:17 INFO     loading libcrypto from libcrypto.so.1.0.0
2015-01-22 09:52:17 INFO     starting local at 127.0.0.1:65500
```
I have always  been using **sslocal** before i find **shadowsocks-qt5**

**Comment by YanceyWang** [comment]
My python version is `Python 2.7.6` 
and **sslocal** works fine for me 
```java
xxx@xxx ~/antiWall $ sslocal -c congfig.json 
INFO: loading config from congfig.json
shadowsocks 2.6.4
2015-01-22 09:52:17 INFO     loading libcrypto from libcrypto.so.1.0.0
2015-01-22 09:52:17 INFO     starting local at 127.0.0.1:65500
```
I have always  been using **sslocal** before i find **shadowsocks-qt5**

**Comment by librehat** [comment]
Starting shadowsocks-qt5 from terminal, and paste the output when you use python port.

`ss-qt5 -v`

**Comment by YanceyWang** [comment]
```javascript
xxx@xxx-m81 ~ $ ss-qt5 -v
Verbose Enabled. 
Maximum pending connections is set to 1024 
"Backend arguments are " " -s 218.251.112.136 -p xxxx -b 127.0.0.1 -l 1080 -k "xxxx" -m aes-256-cfb -t 600 -v --fast-open " 
"Backend started. PID: " 30277 
"2015-01-23 10:55:16 INFO     loading libcrypto from libcrypto.so.1.0.0" 
"2015-01-23 10:55:16 INFO     starting local at 127.0.0.1:1080" 
"2015-01-23 10:55:16 ERROR    [Errno 98] Address already in use" 
"Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/local.py", line 60, in main" 
"udp_server = udprelay.UDPRelay(config, dns_resolver, True)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/udprelay.py", line 127, in __init__" 
"server_socket.bind((self._listen_addr, self._listen_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth" 
"return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use" 
"Backend exited. Exit Code: " 1
```

**Comment by librehat** [comment]
Are you sure port 1080 is not used? Run `netstat -nlp | grep 1080` before `ss-qt5`, can you see if 1080 is in used already?

Because the previous `sslocal` command you supplied is to use 65500 port.

**Comment by YanceyWang** [comment]
ahh，Finally, it works!!
